#' MixTCRviz: Plot TCR motifs
#'
#' MixTCRviz is an R package to display TCR motifs for a set of TCRs provided by the user.
#' Typically, the input TCRs correspond to TCRs binding to a specific epitope, or isolated in a specific experiment.
#' MixTCRviz compares V usage, J usage, CDR3 length distribution and CDR3 sequence motifs to those expected from baseline TCR repertoire.
#' Mandatory parameters.
#'
#' @param input1 Either a .csv or .txt or .tsv file with the input TCRs, or a data.frame with the input TCRs, or list in the MixTCRviz format. 
#'    * Columns should ideally include "TRAV","TRAJ","cdr3_TRA","TRBV","TRBJ","cdr3_TRB" (one chain is allowed if chain.list.output = "A" or "B", respectively)
#'    * If TCRs from multiple experiments/epitopes/classses/... are provided in the same file, the "model" column should indicate the models
#'    ("Model_default" is used by default if no "model" column is provided and model.default=NULL, see below). The use of multiple model is only possible in input1.
#'    * If TCRs from multiple species are provided in the same file, the "species" should indicate the species of the TCRs
#'    ("HomoSapiens" or "MusMusculus", with "HomoSapiens" being the default if no "species" column and species.default=NULL)
#'    * The "TRAV", "TRAJ", "TRBV", "TRBJ" should follow the IMGT
#'   nomenclature, with or without allele (see below for potential name correction).
#'   If a column is missing, empty values will be used.
#'    * The "cdr3_TRA" and "cdr3_TRB" columns should provide CDR3A/CDR3B sequences, following the standard definition (e.g., CAVNSDGQKLLF).
#'   Cases with non-amino acid characters, or length < 7 or > 22 will be not be considered (i.e., put to NA).
#'   If a column is missing, empty values will be used.
#'    * Other formats are supported (see README.md)
#' @param output.path name of the output directory (if not already existing, it
#'   will be created). If existing the files with the same name will be overwritten.
#'   It can be left empty ONLY with the option return.object=2.
#'   
#'  Optional parameters 
#'   
#' @param input2 (default=NULL): .csv file or data.frame containing a second set of
#'   TCRs to be used in comparisons. Same format as input1, except that all TCRs are assumed to come from a single model so any data in the "model" field is omitted.
#'   If input2 is provided, the comparisons is performed with this second input, and not the baseline
#'   repertoire. In this case, all models provided in input1 will be compared with the repertoire in input2, and multiple species should not be mixed in input1.
#'   Other than .csv filename or data.frame, a third alternative consists of a list or .rds file with precomputed statistics,
#'   such as those generated by MixTCRviz::build_stat() function.
#'   
#' @param baseline (default=NULL) R object (list) or name of a .rds/.rda/.rdata file containing all data about the
#'   baseline repertoire to be used, in the same format as the default repertoires.
#'   If .rda file, the object containing the data about the repertoires must be called 'baseline'.
#'   Alternatively one of the strings: "Default" or "SEQTR" for data in input1 generated by publicly available TCR-seq approaches (Default) or SEQTR (SEQTR) protocols
#'   If empty, the default baseline repertoires are used.
#'   
#' @param use.allele (default=FALSE)
#'    * FALSE: All V/J alleles are merged at the gene level (recommended).
#'    * TRUE: Alleles are kept. If some entries do not include alleles, the most frequent one is added.
#'   Currently, use.allele is fixed to FALSE for mouse TCRs.
#'   
#' @param correct.gene.names (default=TRUE)
#'    * F: Do not attempt to correct V/J gene names. Put to NA genes not in IMGT.
#'    * T: Attempt to correct V/J gene names not in IMGT based on our internal dictionary.
#'     Put to NA genes that could not be corrected
#'     
#' @param use.mouse.strain (default=FALSE)
#'    * FALSE: Merge the different TRAV genes corresponding to different mouse strains (e.g., TRAV10D, TRAVN10 and TRAV10 become all TRAV10).
#'   This is recommended since differences between input TCRs and baseline TCRs
#'   may result from the use of different mouse strains, and not be related to
#'   specificity in input TCRs. In addition different TCR reconstruction tools
#'   use different approaches to call these genes, which can create artificial
#'   enrichment in one of them versus the baseline.
#'    * TRUE: The different TRAV segments (e.g., TRAV10D, TRAVN10 and TRAV10) are treated separately.
#'    
#' @param check.cdr3.mode (default=1)
#'    * 0: Keep all CDR3 without any correction.
#'    * 1: Remove V and CDR3 when the first start.lg CDR3 amino acids are incompatible with the V segment;
#'        Remove J and CDR3 when the last end.lg amino acids are not compatible with the J segments.
#'        Allow compatibility check with any allele.
#'        
#' @param start.lg (default=1): Number of amino acids to be checked for compatibility between V segment and beginning of CDR3
#'      Needs to be an integer between 0 and 3.
#' 
#' @param end.lg (default=2): Number of amino acids to be checked for compatibility between J segment and end of CDR3
#'      Needs to be an integer between 0 and 5.
#'       
#' @param renormVJ (default=NULL)
#'    * NULL: If left empty, 1 is used if comparison is performed with a baseline (input2==NULL) 
#'      and 0 is used if comparison is performed with input2 (i.e., input2 != NULL)
#'    * 0: Compare CDR3 length distribution and motif with those from the baseline repertoire or input2
#'    * 1: Compare CDR3 length distribution and motif with those from the baseline repertoire with the V-J
#'   usage observed in the input TCRs. In the plots the mark " | P(VJ)" is used to
#'   indicate that CDR3 length distributions and motifs correspond to those
#'   expected with the V-J usage in the TCRs used for training.
#'   
#' @param N.min (default=1) Minimum number of TCR (i.e., V-J-CDR3) for at least
#'   one chain. This number is computed after cleaning the data.
#'   
#' @param output.stat (default=FALSE) 
#'    * FALSE: Do not print the stat to a file
#'    * TRUE: create a output.path/stat/ folder with .rds files summarizing the raw statistics for each model. Only supported if return.object != 2 
#'   
#' @param output.processed.data (default=FALSE)
#'    * FALSE: Do not print the processed/clean data to a file
#'    * TRUE: create a output.path/processed_data/ folder with the data for each model after the different processing steps
#'   (e.g., removing alleles, correcting V/J names, removing inconsistent CDR3, etc. depending on the cleaning option selected). 
#'   Only supported if return.object != 2 
#'   
#' @param set.cdr3a.length (default=NA) Length for the CDR3a motif to be shown in the main plot.
#'   By default the value corresponding to the most frequent CDR3a length in input1 (and also present in input2 if input2 is given) is chosen.
#'   
#' @param set.cdr3b.length (default=NA) Length for the CDR3b motif to be shown in the main plot.
#'   By default the value corresponding to the most frequent CDR3b length in input1 (and also present in input2 if input2 is given) is chosen.
#'   
#' @param species.default (default="HomoSapiens"). Option to provide the species for all the TCR in input.
#'   This is useful if your input does not contain a "species" column.
#'   In case the input contains the "species" column, species.default is not considered.
#'   Should be either "HomoSapiens" or "MusMusculus"
#'   
#' @param model.default (default="Model_default") Option to provide the model for all the TCR in input, which is also used as the name of the output files.
#'   This is useful if your input does not contain a "model" column.
#'   In case the input contains the "model" column, model.default is not considered.
#'   
#' @param verbose (default=1)
#'    * 0: Do not write any QC in the output
#'    * 1: Write max 10 examples of putative issues with the data (V/J names, CDR3 sequences, etc.) in the terminal
#'    * 2: Write all the putative issues with the data (V/J names, CDR3 sequences, etc.) in the terminal
#'    * 3: Write all putative issues + cases that were corrected
#'       
#' @param plot (default=TRUE)
#'    * F: Do not build the motifs. This overrides plot.all.length=T and interactive.plots=T
#'    * T: Build the motifs
#'    
#' @param plot.cdr12.motif (default=FALSE)
#'    * F: Only show motifs for CDR3 of the most frequent length.
#'    * T: Include sequence motifs for CDR1 and CDR2. With this choice, plot.oneline is set to 0.
#'    
#' @param plot.oneline (default=0)
#'    * 0: Show the data on two lines (better for clarity).
#'    * 1: Show all plots in a single line (can be useful to compare different models).
#'    * 2: Show only V/J usage and length (i.e., do not show CDR3 motifs for the most frequent CDR3 length)
#'    
#' @param plot.all.length (default=FALSE)
#'    * F: Show only the CDR3 motifs for the most frequent CDR3 length.
#'    * T: Write in output.path/CDR3_length separate plot the V usage, J usage and CDR3 motifs
#'     for all CDR3 length. Only applicable if return.object != 2 and plot=T.
#'    
#' @param plot.cdr3.norm (default=0)
#'    * 0: Show the CDR3 motifs of the input and of the baseline repertoire or input2, possibly | P(VJ).
#'    * 1: Show the CDR3 motifs of the input TCRs after subtracting the baseline repertoire (not recommended).
#'    * 2: Show the CDR3 motifs of the input TCRs after normalising by the baseline repertoire (motif of normalised fold-change, not recommended)
#'    
#' @param plot.sd (default=T)
#'    * T: Show standard deviation for P(V), P(J) and P(L), if such data are provided for baseline and/or input1 
#'    * F: Do not show standard deviation
#'    
#' @param plot.VJ.switch (default=1)
#'    * 1: Show the VJ usage as a scatter plot with inner colors, outer colors and shapes of the points based
#'       on the V/J gene names (see lookup table in MixTCRviz/figures/, scheme1).
#'    * 1.2: Show the VJ usage as a scatter plot with colors of the points based
#'       on the V/J gene names (see lookup table in MixTCRviz/figures/, scheme2).
#'    * 1.3: Show the VJ usage as a scatter plot with black points and V/J gene label in colors (see lookup table in MixTCRviz/figures/, scheme2).
#'    * 2: Show the VJ usage as a bar plot (see lookup table in MixTCRviz/figures/, scheme2).
#'    
#' @param plot.modelsCombined (default=FALSE)
#'    * FALSE or empty string: Show the data for each model separately.
#'    * TRUE or a string: Show the data for all models combined in a single
#'        figure (based on the format plot.VJ.switch=2). When given as a
#'        logical, the default name "modCombined" is used. Otherwise, the string
#'        is used for the resulting figure filename.
#'        
#' @param label.neg (default=FALSE): If TRUE, show also the labels of the genes most depleted in input1.
#' 
#' @param label.diag (default=0.3): Decide to keep some label in the upper right corner, based on label.diag value. 
#'        This can be useful when comparing two epitope-specific TCRs
#'
#' @param label.min.fr (default=c(0.05,0.05)): Region (i.e., X - Y rectangle) of the left corner of V/J plots with no gene label. 
#' If only one number is provided, it will be used on both the X and Y axes.
#' 
#' @param keep.incomplete.chain (default=T): If False, incomplete chains are discarded. 
#'      Even if input only consists of complete chains, incomplete chain can occur when one V/J gene cannot be corrected, 
#'      or when there is some incompatibilities between V/J names and CDR3 sequences
#' 
#' @param chain.list.output (default="AB")
#'    * A: Only the alpha chain is plotted in output;
#'    * B: only the beta chain is plotted in output;
#'    * AB both chains are plotted in output
#'    
#' @param input1.name (default="Input"): Provide a generic name for
#'   the input TCRs in the plots (e.g., Epitope Specific). Avoid names with more
#'   than 20 characters
#'   
#' @param input2.name (default=NULL): If a second set of TCRs is provided
#'   (i.e., input2 != NULL), Provide a generic name for the input2 TCRs in the
#'   plots. Avoid names with more than 20 characters.
#'   
#' @param output.format (default="pdf"): Choose the format for the output
#'      plots (can be "pdf", "png" or "jpg").
#'      
#' @param interactive.plots (default=F): 
#'    * F: Do not create an html file with interactive plots. 
#'    * T: Create an html file with interactive plots. Only applicable if return.object != 2 and plot=T
#'      
#' @param print.size (default=TRUE): If TRUE, print the number of TCRs in input1 in the plots.
#' 
#' @param plot.title (default=TRUE): If TRUE, print the model name as title to the plots.
#' 
#' @param set.title (default=NULL): Set the title of the plots. If empty, model names in input1 are used as title.
#' 
#' @param build.clones (default=F): If TRUE and if the data are provided in format with clone.id, reconstruct the actual clones in output
#'  
#' @param keep.colnames.origin (default=F): If TRUE, keep the name of the columns dedicated the TCRs in the input. The option is not supported for format with clone.id
#' 
#' @param return.object (default=0): 
#'    * 0: do not return any object.
#'    * 1: return an object with plots ($plot, if plot=T), statistics ($stat) and processed.data ($processed.data, if input1 is not a precomputed list with the stat) for each model
#'    * 2: Only return an object and do not write anything to file. In this case output.path can be omitted
#'    Plots can be displayed in R studio, for instance.
#'    Quality will vary depending on your R studio settings, so this option is not recommended for high-quality figures. 
#'    
#'
#' @returns Nothing.
#' @export
MixTCRviz <- function(input1, output.path=NULL,
                      input2=NULL, baseline=NULL,
                      use.allele=F, correct.gene.names=T, use.mouse.strain=F, check.cdr3.mode=1, start.lg=1, end.lg=2,
                      renormVJ=NULL, N.min=1, output.stat=F, output.processed.data=F, 
                      set.cdr3a.length=NA, set.cdr3b.length=NA, plot.title=T, set.title=NULL, return.object=0,
                      species.default="HomoSapiens", model.default="Model_default", verbose=1, build.clones=F,
                      plot=T, plot.cdr12.motif=F, plot.oneline=0, plot.all.length=F, plot.cdr3.norm=0,
                      plot.VJ.switch=1, plot.modelsCombined=FALSE, label.neg=F, label.diag=0.3, plot.sd=T,
                      label.min.fr=c(0.05,0.05), chain.list.output="AB", keep.incomplete.chain=T,
                      input1.name="Input", input2.name=NULL, output.format="pdf", keep.colnames.origin=F,
                      interactive.plots = F, print.size=T){
  
  
  #######
  # Check input parameters
  #######
  
  if(!is.logical(output.stat)){
    print("Invalid value for output.stat. Default value of FALSE will be used")
    output.stat <- F
  }
  
  if(!is.logical(output.processed.data)){
    print("Invalid value for output.processed.data. Default value of FALSE will be used")
    output.processed.data <- F
  }
  
  if(!is.logical(interactive.plots)){
    print("Invalid value for interactive.plots Default value of FALSE will be used")
    interactive.plots <- F
  }
  
  if(! return.object %in% c(0,1,2)){
    print("Invalid value for return.object. Default value of 0 will be used")
    return.object <- 0
  }
  
  if(!is.logical(plot.all.length)){
    print("Invalid value for plot.all.length. Default value of FALSE will be used")
    plot.all.length <- F
  }
  
  if(!is.logical(plot)){
    print("Invalid value for plot. Default value of TRUE will be used")
    plot <- T
  }
  if(!plot){
    print("No motif will be generated with plot=FALSE")
  }
  
  if(return.object==0 | return.object==1){
    if (is.null(output.path)){
      stop("Invalid value for output.path. Output.path can only be omitted if return.object=2")
    } else if(!is.character(output.path) | length(output.path)>1){
      stop("Invalid value for output.path. Should be a single string of character indicating path where to save the plots.")
    } 
  } else {
    if(plot){
      print("Motifs and data will only be returned as a list, and not printed to any file.")
    } else {
      print("Data will only be returned as a list, and not printed to any file.")
    }
    if(plot.all.length){
      print("plot.all.length=T is not supported with return.object=2. Will be set to FALSE")
      plot.all.length <- F
    }
    if(interactive.plots){
      print("interactive.plots=T is not supported with return.object=2. Will be set to FALSE")
      interactive.plots <- F
    }
    if(output.stat){
      print("output.stat=T is not supported with return.object=2. Will be set to FALSE")
      output.stat <- F
    }
    if(output.processed.data){
      print("output.processed.data=T is not supported with return.object=2. Will be set to FALSE")
      output.processed.data <- F
    }
  }
  
  if(!is.logical(use.allele)){
    print("Invalid value for use.allele. Default value of FALSE will be used")
    use.allele <- F
  }
  
  if(!is.logical(correct.gene.names)){
    print("Invalid value for correct.gene.names. Default value of TRUE will be used")
    correct.gene.names <- T
  }
  if(correct.gene.names==F){
    print("Warning: the option to correct V/J names is turned off. You need to be sure all your V/J names follow the IMGT nomenclature")
  }
  
  if(!is.logical(use.mouse.strain)){
    print("Invalid value for use.mouse.strain. Default value of FALSE will be used")
    use.mouse.strain <- F
  }
  
  if(!check.cdr3.mode %in% c(0,1,2)){
    print("Invalid value for check.cdr3.mode. Default value of 1 will be used")
    check.cdr3.mode <- 1
  }
  
  if(!start.lg %in% 0:3){
    print("Invalid value for start.lg. Default value of 1 will be used")
    start.lg <- 1
  }
  
  if(!end.lg %in% 0:5){
    print("Invalid value for end.lg. Default value of 2 will be used")
    end.lg <- 2
  }
  if(!is.logical(build.clones)){
    print("Invalid value for build.clones. Default value of FALSE will be used")
    build.clones <- F
  }
  
  
  if(is.null(renormVJ)){
    renormVJ <- ifelse(is.null(input2),T,F)
  } else {
    if(!is.logical(renormVJ)){
      print(paste("renormVJ=",renormVJ," not supported, default value will be used", sep=""))
      renormVJ <- ifelse(is.null(input2),T,F)
    } else {
      renormVJ <- renormVJ
    }
  }
  
  if(N.min < 1 | is.numeric(N.min)==FALSE){
    print(paste("N.min=",N.min," not supported, using default N.min=1", sep=""))
    N.min <- 1
  }
  
  
  
  if(!is.na(set.cdr3a.length)){
    if(is.numeric(set.cdr3a.length)==F | set.cdr3a.length < Lmin | set.cdr3a.length > Lmax | set.cdr3a.length%%1 != 0){
      print(paste("Invalid value for set.cdr3a.length",set.cdr3a.length,". Default value will be used.", sep=""))
      set.cdr3a.length=NA
    }
  }
  if(!is.na(set.cdr3b.length)){
    if(is.numeric(set.cdr3b.length)==F | set.cdr3b.length < Lmin | set.cdr3b.length > Lmax | set.cdr3b.length%%1 != 0){
      print(paste("Invalid value for set.cdr3b.length=",set.cdr3b.length,". Default value will be used.", sep=""))
      set.cdr3b.length=NA
    }
  }
  
  if(! species.default %in% species.list){
    print("Wrong choice for species.default. Should be either \"HomoSapiens\" or \"MusMusculus\". Default value will be used")
    species.default <- "HomoSapiens"
  }
  
  if(!is.character(model.default) | length(model.default)>1){
    print(paste("Invalid value for model.default",model.default,". Default value will be used.", sep=""))
    model.default="Model_default"
  }
  
  if(! verbose %in% 0:3){
    print("Invalid value for verbose. Default value of 1 will be used")
    verbose <- 1
  }
  
  
  
  if(!is.logical(plot.cdr12.motif)){
    print("Invalid value for plot.cdr12.motif. Default value of FALSE will be used")
    plot.cdr12.motif <- F
  }
  
  if(!plot.oneline %in% c(0,1,2)){
    print("Invalid value for plot.oneline. Default value of 0 will be used")
    plot.oneline <- 0
  }
  
  if(! plot.cdr3.norm %in% c(0,1,2) ){
    print("Invalid value for plot.cdr3.norm. Default value of 0 will be used")
    plot.cdr3.norm <- 0
  }
  
  if(! plot.VJ.switch %in% c(1,1.2,1.3,2)){
    print("Invalid value for plot.VJ.switch. Default value of 1 will be used")
    v$plot.VJ.switch <- 1
  }
  
  if(!is.logical(label.neg)){
    print("Invalid value for label.neg. Default value of FALSE will be used")
    label.neg <- F
  }
  
  if(!is.numeric(label.diag) | label.diag<0){
    print("Invalid value for label.diag. Should be a number larger than 0. Default value of 0.3 will be used")
    label.neg <- 0.3
  }
  
  if(!is.numeric(label.min.fr) | !length(label.min.fr) %in% c(1,2) | max(label.min.fr)>1 | min(label.min.fr)<0){
    print("Invalid value for label.min.fr. Default value of c(0.05,0.05) will be used")
    label.min.fr <- c(0.05,0.05)
  } else if(length(label.min.fr)==1){
    label.min.fr <- c(label.min.fr,label.min.fr)
  }
  
  if(! chain.list.output %in% c("A","B","AB")){
    print("Invalid value for chain.list.output. Default value of \"AB\" will be used")
    chain.list.output <- "AB"
  }
  
  if(!is.character(input1.name)){
    print("Invalid value for input1.name. Default value of \"Input\" will be used")
    input1.name <- "Input"
  }
  
  if(! output.format %in% c("pdf", "png", "jpg")){
    print("Invalid value for output.format. Default value of \"pdf\" will be used")
    output.format <- "pdf"
  }
  
  if(!is.logical(print.size)){
    print("Invalid value for print.size. Default value of TRUE will be used")
    print.size <- T
  }
  
  
  if(!is.logical(plot.title)){
    print("Invalid value for plot.title. Default value of TRUE will be used")
    plot.title <- T
  }
  
  if(!is.null(set.title)){
    if(!is.character(set.title) | length(set.title)!=1){
      print("Invalid value for set.title. Model names will be used")
      set.title=NULL
    }
  }
  
  modelsCombinded_name <- "modCombined"
  if (is.character(plot.modelsCombined)){
    if (plot.modelsCombined == ""){
      plot.modelsCombined <- F
    } else {
      modelsCombinded_name <- plot.modelsCombined
      plot.modelsCombined <- T
    }
  }
  if (plot.modelsCombined && !(plot.VJ.switch %in% c(2))){
    warning("plot.modelsCombined is set to TRUE, and plot.VJ.switch wasn't '2'.",
            "Setting plot.VJ.switch=2 as other VJ plot format is not available",
            "when combining results from all models in a single plot.")
    plot.VJ.switch <- 2
  }
  
  ###########
  #Set some specific values for different parameters
  ###########
  
  
  
  keep.gap.pwm <- 0 # 1: means that 'g' (gaps in CDR1/2) are treated as an additional aa in the logos. 0: means that 'g' are treated as unspecific (i.e., 0.05) in the logos
  if(keep.gap.pwm==1){taa.list <- c(aa.list,"g"); additionalAA <- "g"} else {taa.list <- aa.list; additionalAA <- ""}
  
  min.logo <- 5 #Minimum number of sequences to plot the logos (when plotting different lengths)
  
  if(plot.oneline>=1){
    th <- theme(plot.title = element_text(size = 8, hjust=0.5), axis.title=element_text(size=4))
  }
  if( return.object != 2 ){
    if(!dir.exists(output.path) ){
      dir.create(output.path, recursive = TRUE);
    }
  }
  
  if(is.null(input2)){
    comp.baseline <- 1
    if(is.null(input2.name)){
      baseline.name <- "Baseline"
    } else if(is.character(input2.name)){
      baseline.name <- input2.name
    } else {
      stop("Invalid value for input2.name. Should be a character or NULL")
    }
  } else if(is.character(input2) | is.data.frame(input2) | is.list(input2)) {
    comp.baseline <- 0
    
    if(is.null(input2.name)){
      baseline.name <- "Input2"
    } else if(is.character(input2.name)){
      baseline.name <- input2.name
    } else {
      stop("Invalid value for input2.name. Should be a character or NULL")
    }
  }
  
  ############################
  # Load all the input data
  ############################
  
  input1.list=F
  if(is.character(input1)==T){
    if(file.exists(input1)){
      ext <- tail(unlist(strsplit(input1,split=".", fixed=T)), n=1)
      if(ext=="csv"){
        input1 <- read.csv(input1)
      } else if(ext=="txt" | ext=="tsv"){
        input1 <- read.delim(input1, sep="\t", header=T)
      } else if (ext=="rds"){
        input1 <- readRDS(input1)
        input1.list <- T
      } else {
        stop("Invalid file format for input2")
      }
    } else {
      stop("Missing file for input1")
    }
  } else if(is.data.frame(input1)==T){
    input1 <- as.data.frame(input1)
    # Use as.data.frame because a tibble is also a data.frame but some of the
    # code has issues if input is a tibble instead of "simpler" data.frame (due
    # to column indexing by a single column that keep it as a tibble while it is
    # transforming it to a vector if a data.frame).
  } else if(is.list(input1)){
    input1.list <- T
  } else {
    stop("Invalid value for input1. Should be a .csv or tab delimited .txt filename or a data.frame or a list generated by MixTCRviz")
  }
  
  
  if(!input1.list){
    
    # Check the compatibility between chain.list.output and the actual data. 
    # If not compatible, try correcting chain.list.output. If impossible, stop the run
    chain.list.output <- verify.chain(input=input1, chain.list.output=chain.list.output)
    if(chain.list.output==""){
      stop("Incompatibilities between the data and chain.list.output, and unable to infer the chain... check your input and the chain.list.output parameter")
    }
  }
  
  if(chain.list.output=="A"){
    chain.list <- c("TRA");
    set.cdr3.length <- c(set.cdr3a.length)
  } else if(chain.list.output=="B"){
    chain.list <- c("TRB");
    set.cdr3.length <- c(set.cdr3b.length)
  } else if(chain.list.output=="AB"){
    chain.list <- c("TRA","TRB");
    set.cdr3.length <- c(set.cdr3a.length, set.cdr3b.length)
  } 
  names(set.cdr3.length) <- chain.list
  
  
  # Check the input
  cat("####\nChecking input1:\n")
  check <- check_input(input=input1, chain.list.output = chain.list.output, name="input1", 
                       species.default = species.default, model.default = model.default,
                       input.list=input1.list, build.clones=build.clones)
  input1 <- check$data
  map.back.colnames <- check$col.map
  
  if(!input1.list){
    input1 <- clean_input(input=input1, use.allele=use.allele, correct.gene.names = correct.gene.names, 
                          use.mouse.strain = use.mouse.strain, chain.list.output = chain.list.output, keep.incomplete.chain = keep.incomplete.chain,
                          species.default = species.default, check.cdr3.mode = check.cdr3.mode, start.lg=start.lg, end.lg=end.lg, verbose=verbose)
  }
  #############
  # Load input2
  #############
  
  if(comp.baseline==0){
    input2.list <- F
    if(is.character(input2)){
      if(file.exists(input2)){
        ext <- tail(unlist(strsplit(input2,split=".", fixed=T)), n=1)
        if(ext=="csv"){
          input2 <- read.csv(input2)
        }else if(ext=="txt" | ext=="tsv"){
          input2 <- read.delim(input2, sep="\t", header=T)
        } else if (ext=="rds"){
          input2 <- readRDS(input2)
          input2.list <- T
        } else {
          stop("Invalid file format for input2")
        }
      } else {
        stop("Missing file for input2")
      }
    } else if(is.data.frame(input2)){
      input2 <- as.data.frame(input2)
      # See comment for input1
    } else if(is.list(input2)){
      input2.list <- T
    } else {
      stop("Invalid value for input2. Should be a .csv filename or a data.frame")
    }
    cat("####\nChecking input2:\n")
    
    if(!input2.list){
      ch <- verify.chain(input=input2, chain.list.output=chain.list.output)
      if(ch != chain.list.output){
        stop("Incompatible chains between input1 and input2")
      }
    }    
    input2 <- check_input(input=input2, chain.list.output=chain.list.output, name="input2", 
                          species.default = species.default, model.default = model.default, input.list=input2.list, build.clones=build.clones())$data
    if(!input2.list){
      input2 <- clean_input(input=input2, use.allele = use.allele, correct.gene.names = correct.gene.names,
                            use.mouse.strain = use.mouse.strain, chain.list.output = chain.list.output, keep.incomplete.chain = keep.incomplete.chain,
                            species.default = species.default, check.cdr3.mode = check.cdr3.mode, start.lg=start.lg, end.lg=end.lg, verbose=verbose)
    }
  }
  
  ########################
  #Select the models which should be considered
  ########################
  
  #Take samples where there is at least one chain with enough data
  if(!input1.list){
    if (is.factor(input1$model)){
      md <- levels(input1$model)
      # When this model is given as a factor, we keep its order (this is useful
      # only for the plot.modelsCombined=TRUE option, to have the models in this
      # order instead of 'random' order).
    } else {
      md <- unique(input1[,"model"])
    }
    st <- lapply(md, function(x){
      i <- which(input1[,"model"]==x);
      nA <- length(which(!is.na(input1[i,"TRAV"]) | !is.na(input1[i,"TRAJ"]) | !is.na(input1[i,"cdr3_TRA"]) ))
      nB <- length(which(!is.na(input1[i,"TRBV"]) | !is.na(input1[i,"TRBJ"]) | !is.na(input1[i,"cdr3_TRB"]) ))
      if( (nA>=N.min & chain.list.output=="A") | (nB>=N.min & chain.list.output=="B") | ((nA>=N.min | nB>=N.min) & chain.list.output=="AB")){
        return(1)
      } else {
        warning("Model ",x," will not be considered (less than N.min=", N.min," data)")
        return(0)
      }
    })
    model.list <- md[st==1]
  } else {
    model.list <- c(input1$model) #In this case, only one model is allowed
  }
  if(length(model.list)==0){
    stop("No model has enough data to use MixTCRviz. Check your input, or the N.min parameter if you set it manually.")
  }
  
  
  #######################################
  # Analyse the input
  #######################################
  
  comb_res <- list()
  if(return.object != 0){
    plot.lst <- list()
    es.lst <- list()
    if(!input1.list){
      input1.lst <- list()
    } else {
      print("Will not be able to return processed data for input1 since it does not contain raw data.")
    }
  }
  
  # Will be used when plot.modelsCombined=TRUE to store values from each model.
  for(model in model.list){
    
    use.allele.es <- use.allele
    
    print(paste("Model:",model))
    
    pg.all <- list()
    interactive_figure <- list()
    pg.length <- list()
    tl.logo <- list() #Keep track of the number of logos of different length
    
    if(!input1.list){
      input1.es <- input1[which(input1[,"model"]==model),]
      species <- unique(input1.es[,"species"])
      if(length(species)>1){
        stop("Multiple species provided for the same model. Use a different model name for each species")
      } else {
        if(species %in% species.list==F){
          stop(paste("Unknown species: ",sp,". MixTCRviz supports only \"HomoSapiens\" or \"MusMusculus\"", sep=""))
        }
      }
      if(species=="MusMusculus" & use.allele.es){
        print("Alleles currently not supported in mouse. The data will be treated at the gene level")
        use.allele.es <- F
      }
      es <- build_stat(input1.es, chain.list=chain.list, species=species, comp.VJL=0)
      es$model <- model
      
      if(return.object != 0){
        input1.lst[[model]] <- input1.es
      }
      
    } else {
      es <- input1
      species <- input1$species
    }
    if(return.object != 0){
      es.lst[[model]] <- es
    }
    
    
    if(output.stat){
      dir <- paste(output.path,"/stats/", sep="")
      if(!dir.exists(dir)){
        dir.create(dir);
      }
      saveRDS(es, file=paste(output.path,"/stats/",model,".rds", sep=""))
    }
    if(output.processed.data){
      if(!input1.list){
        dir <- paste(output.path,"/processed_data/", sep="")
        if(!dir.exists(dir)){
          dir.create(dir);
        }
        tinput1.es <- input1.es
        
        if(keep.colnames.origin){
          cn <- colnames(input1.es)
          if(length(map.back.colnames)>0){
            for(i in 1:length(cn)){
              if(!is.null(map.back.colnames[[cn[i]]])){
                cn[i] <- map.back.colnames[[cn[i]]]
              }
            }
          }
          colnames(tinput1.es) <- cn
        }
        quote_if_comma <- function(x) {  ifelse(grepl(",", x), paste0('"', x, '"'), x) }
        tinput1.es <- as.data.frame(apply(tinput1.es, 2, function(col) { if (is.character(col)) quote_if_comma(col) else col }))
        
        write.csv(tinput1.es, file=paste(output.path,"/processed_data/",model,".csv", sep=""), quote=F, row.names = F, na = "")
      }
    }
    
    if(plot){
      
      if(comp.baseline==1){
        
        #####
        # Load the baseline repertoire corresponding to the species
        #####
        
        if(is.null(baseline)){
          
          #These are the default repertoires.
          if(species=="HomoSapiens"){
            if(use.allele.es){
              baseline <-  MixTCRviz::baseline_HomoSapiens_allele
            } else {
              baseline <- MixTCRviz::baseline_HomoSapiens
            }
          }
          if(species=="MusMusculus"){
            if(!use.allele.es){  #N.B. Currently always the case in mouse
              if(use.mouse.strain){
                baseline <- MixTCRviz::baseline_MusMusculus_Strain
              } else {
                baseline <- MixTCRviz::baseline_MusMusculus
              }
            }
          }
        } else if(is.character(baseline)) {
          if(baseline=="SEQTR"){
            if(use.allele==T){
              print("SEQTR is used as baseline, alleles will be discarded")
            }
            use.allele=F
            
            if(species=="HomoSapiens"){
              baseline <- MixTCRviz::baseline_HomoSapiens_SEQTR
            } else if(species=="MusMusculus"){
              if(use.mouse.strain){
                baseline <- MixTCRviz::baseline_MusMusculus_Strain_SEQTR
              } else{
                baseline <- MixTCRviz::baseline_MusMusculus_SEQTR
              }
            }
          } else if(baseline=="Default"){
            if(species=="HomoSapiens"){
              if(use.allele){
                baseline <- MixTCRviz::baseline_HomoSapiens_allele
              } else {
                baseline <- MixTCRviz::baseline_HomoSapiens
              }
            } else if(species=="MusMusculus"){
              if(use.mouse.strain){
                baseline <- MixTCRviz::baseline_MusMusculus_Strain_SEQTR
              } else {
                baseline <- MixTCRviz::baseline_MusMusculus_SEQTR
              }
            }
          } else if(file.exists(baseline)){
            st <- strsplit(baseline, split=".", fixed = T)[[1]]
            if(st[length(st)]=="rds"){
              baseline <- readRDS(file=baseline)
            } else if(st[length(st)]=="rda" | st[length(st)]=="rdata"){
              load(baseline)
            } else{
              stop("Unsupported format for baseline file. Should be .rds, .rda or .rdata")
            }
            #Here we should have a way to check the baseline data...
          } else {
            stop("Missing baseline file")
          }
        } else if (is.list(baseline)){
          baseline <- baseline
        } else {
          stop("Unable to use the baseline provided in input")
        }
        
      } else {
        
        #####
        # Load the other repertoire to compare with
        #####
        if (plot.modelsCombined){
          stop("The plot.modelsCombined isn't implemented for comparisons with ",
               "additional input2 data instead of a baseline repertoire.")
        }
        if(!input2.list){
          baseline <- build_stat(input2, chain.list=chain.list, species=species, comp.VJL=renormVJ)
        } else {
          baseline <- input2
          
          if(input2$species != species){
            stop(paste("Different species between input1 (",model,") and input2.", sep=""))
          }
        }
      }
      
      for(chain in chain.list){
        
        #print(chain)
        
        if(comp.baseline==1){
          #Check segments that were in the ES, but not in baseline
          miss.V.baseline <- setdiff(names(es$countV[[chain]]), names(baseline$countV[[chain]]))
          miss.J.baseline <- setdiff(names(es$countJ[[chain]]), names(baseline$countJ[[chain]]))
          if(verbose>0){
            if(length(miss.V.baseline)>=1){
              print(paste("WARNING: ",chain,"V in Input TCRs, but absent from baseline: ", sep=""))
              print(miss.V.baseline)
            }
            if(length(miss.J.baseline)>=1){
              print(paste("WARNING: ",chain,"J in Input TCRs, but absent from baseline: ", sep=""))
              print(miss.J.baseline)
            }
          }
        }
        
        if(verbose>0){
          if(length(es$countL[[chain]])==0){
            print(paste("WARNING: No CDR3", chain.small[chain]," segment in input1", sep=""))
          }
          if(length(es$countV[[chain]])==0){
            print(paste("WARNING: No ", chain,"V segment in input1", sep=""))
          }
          if(length(es$countJ[[chain]])==0){
            print(paste("WARNING: No ",chain,"J segment in input1", sep=""))
          }
          
          if(comp.baseline==0){
            if(length(baseline$countL[[chain]])==0){
              print(paste("WARNING: No CDR3", chain.small[chain]," segment in input2", sep=""))
            }
            if(length(baseline$countV[[chain]])==0){
              print(paste("WARNING: No ", chain,"V segment in input2", sep=""))
            }
            if(length(baseline$countJ[[chain]])==0){
              print(paste("WARNING: No ",chain,"J segment in input2", sep=""))
            }
          }
        }
        
        #######
        # Plot length distribution
        #######
        
        if(length(es$countL[[chain]])>0 & length(baseline$countL[[chain]])>0){
          info <- c(chain.small[chain], input1.name, baseline.name, model)
          names(info) <- c("chain", "input1.name", "baseline.name", "model")
          if(print.size){
            info["input1.name"] <- paste(info["input1.name"], " (", sum(es$countL[[chain]]),")",sep="")
            
            if(comp.baseline==0){
              info["baseline.name"] <- paste(info["baseline.name"], " (", sum(baseline$countL[[chain]]),")",sep="")
            }
          }
          
          if(renormVJ==1){
            if(length(es$countVJ[[chain]])>0 & !is.null(baseline$countL.VJ[[chain]])){
              info["baseline.name"] <- paste(info["baseline.name"], "P(VJ)",sep=" | ")
              bs <- weighted_countL(baseline$countL.VJ[[chain]], es$countVJ[[chain]])
              
            } else {
              if(length(es$countVJ[[chain]])==0){
                print(paste("No P(VJ) information in input1 to compute baseline CDR3",chain.small[chain]," length distribution | P(VJ). renormVJ=0 will be used", sep=""))
              }
              if(is.null(baseline$countL.VJ[[chain]])){
                print(paste("No P(L|VJ) information in baseline/input2 to compute baseline CDR3",chain.small[chain]," length distribution | P(VJ). renormVJ=0 will be used", sep=""))
              }
              bs <- baseline$countL[[chain]]
            }
          } else{
            bs <- baseline$countL[[chain]]
          }
          bs.sd <- baseline$sdL[[chain]] # This means that we do not change the sd values, irrespective of | P(VJ)
          
          #baseline$sdL[[chain]] <- 0.2*baseline$countL[[chain]]/sum(baseline$countL[[chain]])
          #es$sdL[[chain]] <- 0.2*es$countL[[chain]]
          
          ld.plot <- plotLD(es$countL[[chain]], bs, info=info, sd.es=es$sdL[[chain]], sd.rep=bs.sd, plot.oneline=plot.oneline,
                            ret.resList=plot.modelsCombined, comp.baseline=comp.baseline, print.size=print.size, plot.sd=plot.sd)
        } else {
          ld.plot <- ggplot()
        }
        
        #######
        # Plot comparison of V/J usage
        #######
        
        if(length(es$countV[[chain]])>0 & length(baseline$countV[[chain]])>0){
          
          infoV <- c(paste(chain,"V", sep=""), input1.name, baseline.name, model)
          names(infoV) <- c("gene", "input1.name", "baseline.name", "model")
          
          countV.plot <- plotVJ(count.es=es$countV[[chain]], count.rep=baseline$countV[[chain]], sd.es=es$sdV[[chain]], sd.rep=baseline$sdV[[chain]],
                                info=infoV, comp.baseline=comp.baseline, pType=plot.VJ.switch, species=species,
                                ret.resList=plot.modelsCombined, label.neg = label.neg, label.diag=label.diag, label.min.fr=label.min.fr, print.size=print.size, plot.sd=plot.sd, verbose=verbose)
        } else {
          #This happens if the baseline is empty for one chain
          countV.plot <- ggplot()
        }
        
        if(length(es$countJ[[chain]])>0 & length(baseline$countJ[[chain]])>0){
          
          infoJ <- c(paste(chain,"J", sep=""), input1.name, baseline.name, model)
          names(infoJ) <- c("gene", "input1.name", "baseline.name", "model")
          
          
          countJ.plot <- plotVJ(count.es=es$countJ[[chain]], count.rep=baseline$countJ[[chain]], sd.es=es$sdJ[[chain]], sd.rep=baseline$sdJ[[chain]],
                                info=infoJ, comp.baseline=comp.baseline, pType=plot.VJ.switch, species=species,
                                ret.resList=plot.modelsCombined, label.neg = label.neg, label.diag=label.diag, label.min.fr=label.min.fr, print.size=print.size, plot.sd=plot.sd, verbose=verbose)
        } else {
          countJ.plot <- ggplot()
        }
        
        #######
        # Plot comparison of motifs for CDR1 and CDR2, but this is redundant with V/J plots
        # No correction based on VJ usage
        #######
        
        logo <- list()
        
        if(plot.cdr12.motif){
          if (plot.modelsCombined){
            stop("The plot.modelsCombined isn't implemented for CDR1/2 motifs.")
          }
          
          if(length(es$countV[[chain]])>0){
            
            for(cdr in c("CDR1", "CDR2")){
              lc <- paste("L",nchar(cdr123[[species]][[chain]][1,cdr]),sep="_")  #Check the length of cdr1 and cdr2
              if(cdr=="CDR1"){
                ct <- es$countCDR1[[chain]][[lc]];
                ylab <- ""; ylab.baseline <- ""
              }
              if(cdr=="CDR2"){
                ct <- es$countCDR2[[chain]][[lc]];
                ylab <- ""; ylab.baseline <- ""
              }
              pwm <- build_cdr12_motif(ct, keep.gap=keep.gap.pwm)  #Useful if we keep the gaps
              logo1 <- ggseqlogoMOD(data=pwm, additionaAA=additionalAA, axisTextSizeX = 10, axisTextSizeY = 10) +
                ggtitle(paste(cdr,chain.small[chain]," ",input1.name," (", sum(es$countV[[chain]]),")",sep="")) + ylab(ylab) + th + theme(plot.title=element_text(size=12))
              #pwm2 <- build_cdr12_motif(ct2, keep.gap=keep.gap.pwm)
              #logo2 <- ggseqlogoMOD(data=pwm2, additionaAA=additionalAA,  axisTextSizeX = 10, axisTextSizeY = 10) +
              #ggtitle(paste(cdr,chain.small[chain]," ",baseline.name," ", sep="")) + ylab(ylab.baseline) + th + theme(plot.title=element_text(size=12))
              #logo[[cdr]] <- ggarrange(logo1, logo2, nrow=2)
              logo[[cdr]] <- ggarrange(logo1, nrow=1)
              
            }
            
          } else {
            for(cdr in c("CDR1", "CDR2")){
              logo[[cdr]] <- ggplot()
            }
          }
        }
        
        #######
        # Plot comparison of motifs of CDR3 for specific lengths
        #######
        
        if(length(es$countL[[chain]])>0){
          
          #Take the length with max Input TCRs
          info <- c(chain.small[chain], input1.name, baseline.name, model)
          names(info) <- c("chain", "input1.name", "baseline.name", "model")
          
          #Here we include a correction based on VJ usage for each length.
          if(renormVJ==1){
            if(max(sapply(es$countVJ.L[[chain]],length))>0 & !is.null(baseline$countCDR3.VJL[[chain]])){  #Make sure we have V-J pairs for at least one length
              info["baseline.name"] <- paste(info["baseline.name"], "P(VJ)",sep=" | ")
              bs <- weighted_countCDR3(baseline$countCDR3.VJL[[chain]], es$countVJ.L[[chain]])
            } else {
              if(max(sapply(es$countVJ.L[[chain]],length))==0){
                print(paste("No P(VJ|L) information in input1 to compute baseline CDR3",chain.small[chain]," motif | P(VJ). renormVJ=0 will be used",sep=""))
              }
              if(is.null(baseline$countCDR3.VJL[[chain]])){
                print(paste("No P(CDR3|VJL) information in baseline/input2 to compute baseline CDR3",chain.small[chain]," motif | P(VJ). renormVJ=0 will be used",sep=""))
              }
              bs <- baseline$countCDR3.L[[chain]]
            }
          } else {
            bs <- baseline$countCDR3.L[[chain]]
          }
          CDR3 <- plotCDR3(es$countL[[chain]], baseline$countL[[chain]], es$countCDR3.L[[chain]],
                           bs, info, comp.baseline, plot.oneline, plot.all.length, plot.cdr3.norm,
                           set.cdr3.length[[chain]], print.size=print.size)
          
          logo.CDR3.L.es <- CDR3$ES
          logo.CDR3.L.baseline <- CDR3$Baseline
          
          if(length(CDR3$length)>0){
            L.inter <- paste("L",CDR3$length, sep="_")
          } else {L.inter <- c()}
          
          lmax <- CDR3$lmax
          
          if (!plot.modelsCombined){
            logo[["CDR3"]] <- ggarrange(CDR3$ES_max, CDR3$Baseline_max, nrow=2)
            
            if(length(es$countVJ.L[[chain]][[paste("L",lmax,sep="_")]])==0){
              print(paste("No P(VJ|L) information in input1 to compute baseline CDR3 | P(VJ) for Lmax=",lmax,". Empty motif will be shown.",sep=""))
              print("  This is typically due to many entries missing V or J information, or wrong V/J names which could not be corrected")
            }
          } else {
            CDR3$ES_max$labels$title <- paste0(model, " - ", CDR3$ES_max$labels$title)
          }
        } else {
          logo.CDR3.L.es <- NULL
          logo.CDR3.L.baseline <- NULL
          CDR3 <- NULL
          logo[["CDR3"]] <- ggplot()
        }
        
        #############
        #Build the full Figure (or save intermediate results for plot.modelsCombined)
        #############
        
        if (!plot.modelsCombined){
          if(plot.cdr12.motif){
            g <- ggarrange(countV.plot, countJ.plot, ld.plot, ncol=3)
            pg.cdr12 <- ggarrange(logo[["CDR1"]], logo[["CDR2"]], ncol=2)
            pg.all[[chain]] <- ggarrange(g, ggarrange(pg.cdr12, CDR3$ES_max, ncol=2, widths=c(1.2,1)), heights=c(1.5,1), nrow=2)
          } else {
            if(plot.oneline==0){
              pg.all[[chain]] <- ggarrange(countV.plot, countJ.plot, ld.plot, logo[["CDR3"]], ncol=2, nrow=2)
            } else if(plot.oneline==1){
              pg.all[[chain]] <- ggarrange(countV.plot, countJ.plot, ld.plot, logo[["CDR3"]], ncol=4, nrow=1)
            } else if(plot.oneline==2){
              pg.all[[chain]] <- ggarrange(countV.plot, countJ.plot, ld.plot, ncol=3, nrow=1)
            }
          }
          if(interactive.plots){
            interactive_figure[[chain]] <- create_interactive_plots(countV.plot,countJ.plot,ld.plot,CDR3,plot.oneline)
          }
        } else {
          # Combine data from current model with data from previous models
          comb_res[[species]][[chain]]$V$count.df <- dplyr::bind_rows(
            comb_res[[species]][[chain]]$V$count.df, countV.plot$count.df)
          comb_res[[species]][[chain]]$V$gene <- union(
            comb_res[[species]][[chain]]$V$gene, countV.plot$gene)
          comb_res[[species]][[chain]]$V$namesToKeep <- union(
            comb_res[[species]][[chain]]$V$namesToKeep, countV.plot$namesToKeep)
          comb_res[[species]][[chain]]$J$count.df <- dplyr::bind_rows(
            comb_res[[species]][[chain]]$J$count.df, countJ.plot$count.df)
          comb_res[[species]][[chain]]$J$gene <- union(
            comb_res[[species]][[chain]]$J$gene, countJ.plot$gene)
          comb_res[[species]][[chain]]$J$namesToKeep <- union(
            comb_res[[species]][[chain]]$J$namesToKeep, countJ.plot$namesToKeep)
          comb_res[[species]][[chain]]$ld$ld.df <- dplyr::bind_rows(
            comb_res[[species]][[chain]]$ld$ld.df, ld.plot$ld.df)
          comb_res[[species]][[chain]]$ld$info <- union(
            comb_res[[species]][[chain]]$ld$info, ld.plot$info)
          comb_res[[species]][[chain]]$CDR3[[model]] <- CDR3$ES_max
        }
        
        
        if(plot.all.length){
          if (plot.modelsCombined){
            stop("The plot.modelsCombined isn't implemented to show the ",
                 "results from various CDR3 lengths.")
          }
          
          tl.logo[[chain]] <- intersect(names(es$countL[[chain]][es$countL[[chain]]>=min.logo]), L.inter) #Currently the min.logo limitation does not apply to L.inter
          
          if(length(tl.logo[[chain]])>0){
            logo.sub <- list()
            logo.sub.baseline <- list()
            
            plotVJ.L <- list()
            ct <- 1
            for(t in tl.logo[[chain]]){
              logo.sub[[ct]] <- logo.CDR3.L.es[[t]]
              logo.sub.baseline[[ct]] <- logo.CDR3.L.baseline[[t]]
              
              #Add the comparison of V/J usage
              infoV <- c(paste(chain,"V", sep=""), input1.name, baseline.name, model)
              names(infoV) <- c("gene", "input1.name", "baseline.name", "model")
              plotV.L <- plotVJ(count.es=es$countV.L[[chain]][[t]], count.rep=baseline$countV.L[[chain]][[t]],
                                info=infoV, comp.baseline = comp.baseline, pType=plot.VJ.switch, species=species, label.neg = label.neg,  label.diag=label.diag,
                                label.min.fr=label.min.fr, print.size=print.size, verbose=verbose)
              infoV <- c(paste(chain,"J", sep=""), input1.name, baseline.name, model)
              names(infoV) <- c("gene", "input1.name", "baseline.name", "model")
              plotJ.L <- plotVJ(count.es=es$countJ.L[[chain]][[t]], count.rep=baseline$countJ.L[[chain]][[t]],
                                info=infoJ, comp.baseline = comp.baseline, pType=plot.VJ.switch, species=species, label.neg = label.neg,  label.diag=label.diag,
                                label.min.fr=label.min.fr, print.size=print.size, verbose=verbose)
              
              plotVJ.L[[ct]] <- ggarrange(plotV.L, plotJ.L, ncol=2, nrow=1)
              
              ct <- ct+1
              
            }
            g1 <- ggarrange(plotlist=plotVJ.L, nrow=length(tl.logo[[chain]]), ncol=1)
            g2 <- ggarrange(plotlist=logo.sub, nrow=length(tl.logo[[chain]]), ncol=1)
            g3 <- ggarrange(plotlist=logo.sub.baseline, nrow=length(tl.logo[[chain]]), ncol=1)
            
            pg.length[[chain]] <- ggarrange(plotlist=list(g1,g2,g3), nrow=1, ncol=3)
            
            
          } else {
            tl.logo[[chain]] <- c()
            pg.length[[chain]] <- ggplot()
          }
          
        }
        #End of the part specific for plotting data
        
        #} else {
        #  #This is the case where no CDR3 is given
        #  pg.all[[chain]] <- ggplot()
        #  pg.length[[chain]] <- ggplot()
        #  tl.logo[[chain]] <- c()
        #  
        #  print(paste("WARNING: No CDR3",chain.small[chain]," data in input1", sep=""))
        #}
      } #End of the loop over both chains
      
      
      if (!plot.modelsCombined){
        if(chain.list.output=="A" | chain.list.output=="B"){   
          pg.both <- pg.all[[chain.list[1]]]; div=2   
          if(interactive.plots){
            combined_both<- interactive_figure[[chain.list[1]]] 
          }
        }
        if(chain.list.output=="AB"){  
          pg.both <- ggarrange(pg.all[[chain.list[1]]], pg.all[[chain.list[2]]], ncol=2); div=1 
          
          if(interactive.plots){
            combined_both<- manipulateWidget::combineWidgets(
              interactive_figure[[chain.list[1]]] , interactive_figure[[chain.list[2]]],
              ncol = 2,
              title = NULL
            )
            
            
          }
        }
        if(plot.title){
          spacer.size=0.02
          spacer <- ggplot() + theme_void() + theme(plot.margin = unit(c(1, 0, 0, 0), "cm"))
          fig <- ggarrange(spacer, pg.both, ncol=1, nrow=2, heights=c(spacer.size,1))
          if(!is.null(set.title)){
            fig <- annotate_figure(fig, top = text_grob(label=set.title, face = "bold", size = 16))
          } else {
            fig <- annotate_figure(fig, top = text_grob(label=model, face = "bold", size = 16))
          }
          fig <- ggarrange(spacer, fig,ncol=1, nrow=2, heights=c(spacer.size,1))
        } else {
          fig <- pg.both
        }
        if(plot.cdr12.motif){
          width <- 20
          height <- 6
        } else {
          if(plot.oneline==0){
            width <- 15
            height <- 8
            desired_width <- "100%"
            style_width <- "auto"
            desired_height <- "100%"
          } else if(plot.oneline==1){
            width <- 20
            height <- 3
            desired_width <- "2500px"
            style_width <- "auto"
            desired_height <- "400px"
          } else if(plot.oneline==2){
            width <- 15
            height <- 3
            desired_width <- "2500px"
            style_width <- "auto"
            desired_height <- "400px"
            
          }
          if(chain.list.output=="A" | chain.list.output=="B"){
            if(plot.oneline==0){
              desired_width <- "100%"
              style_width <- "50%"
              desired_height <- "100%"
            }else if(plot.oneline==1){
              desired_width <- "1250px"
              style_width <- "75%"
              desired_height <- "400px"
            }else if(plot.oneline==2){
              desired_width <- "1200px"
              style_width <- "70%"
              desired_height <- "400px"
            }
            
          }
        }
        if(return.object != 2){
          ggsave(fig, filename=paste(output.path,"/",model,".", output.format, sep=""), device=output.format, width = width/div, height = height)
        }
        if(return.object != 0){
          plot.lst[[model]] <- fig
        }
        if(interactive.plots){
          
          # Create JavaScript code with simple string concatenation
          if(!is.null(set.title)){
            ttl <- set.title
          } else {
            ttl <- model
          }
          if(!plot.title){
            ttl <- ""
          }
          js_code <- paste0(
            "
              function(el, x) {
                var parentDiv = el.parentNode;
            
                // Style for the title
                var titleDiv = document.createElement('div');
                titleDiv.innerHTML = '", ttl, "';
                titleDiv.style.textAlign = 'center';
                titleDiv.style.fontSize = '24px';
                titleDiv.style.fontWeight = 'bold';
                titleDiv.style.position = 'fixed';
                titleDiv.style.top = '20px';
                titleDiv.style.width = '100%';
                titleDiv.style.backgroundColor = 'white';
                titleDiv.style.zIndex = '1000';
                titleDiv.style.padding = '10px 0';
                document.body.insertBefore(titleDiv, document.body.firstChild);
            
                // Adjust the parent div of the widget
                parentDiv.style.overflowX = 'auto'; // Add horizontal scroll
                parentDiv.style.overflowY = 'hidden'; // Disable vertical scroll
                parentDiv.style.width = '", style_width, "'; // Set parent div width to less than full width to see margin effect
                parentDiv.style.margin = '50px auto 0 auto'; // Center horizontally with automatic margins and add top margin for title
                el.style.display = 'inline-block'; // Set widget to inline-block to prevent squeezing
                el.style.width = '", desired_width, "'; // Adjust this width to allow enough room for the plots
                el.style.height = '", desired_height, "';  // Height for better visibility
              }
            "
          )
          
          html_file <-paste(output.path,"/",model,".html", sep="")
          
          scrollable_combined_figure <- htmlwidgets::onRender(
            combined_both,
            js_code
          )          
          htmlwidgets::saveWidget(scrollable_combined_figure, file = html_file, selfcontained = TRUE)
          
          # Get the name of the folder that may have been created
          folder_name <- sub(".html$", "_files", html_file)
          
          # Delete the folder if it exists
          if (dir.exists(folder_name)) {
            unlink(folder_name, recursive = TRUE)
          }
        }
        if(plot.all.length){
          dir.length <- paste(output.path,"/CDR3_length/", sep="")
          if(!dir.exists(dir.length)){
            dir.create(dir.length);
          }
          
          for(chain in chain.list){
            g.final <- pg.length[[chain]];
            mx <- length(tl.logo[[chain]])
            if(mx>0){
              if(!is.null(output.path)){
                ggsave(g.final, filename=paste(dir.length, model,"_",chain,".", output.format, sep=""), device=output.format, width = 20, height = 2.5*mx)
              }
            }
          }
        }
      }
    }
  }
  if (plot.modelsCombined && plot){
    
    # First, a little test to see if there seem to be inconsistencies between
    # the various models in the sense that some descriptors weren't the same.
    purrr::iwalk(comb_res, .f=function(resSp, species){
      purrr::iwalk(resSp, .f=function(resCh, chain){
        purrr::walk2(c("V", "J", "ld"), c("gene", "gene", "info"), .f=function(x, y){
          if (length(resCh[[x]][[y]]) > 1){
            stop(paste0("The length of comb_res[[", species, "]][[", chain, "]][[",
                        x, "]][[", y, "]] seems inconsistent, having more than 1 value ",
                        "after combining models."))
          }
        })
      })
    })
    
    purrr::iwalk(comb_res, .f=function(resSp, species){
      # The 1st level of comb_res is the species. We'll make separate plot
      # per species as there aren't the same genes.
      for (chain in chain.list){
        # The 2nd level of comb_res is the chain.
        ld.plot <- plotLD(combined.resList=resSp[[chain]]$ld)
        countV.plot <- plotVJ(pType=plot.VJ.switch, species=species,
                              combined.resList=resSp[[chain]]$V, verbose=verbose)
        countJ.plot <- plotVJ(pType=plot.VJ.switch, species=species,
                              combined.resList=resSp[[chain]]$J, verbose=verbose)
        CDR3_logos <- ggarrange(plotlist=resSp[[chain]]$CDR3, ncol=1)
        
        VJ.plot <- ggarrange(countV.plot, countJ.plot, nrow=1,
                             common.legend=T, legend="right")
        # We arrange them together, keeping a single legend as it's the same.
        ld_CDR3logo_plot <- ggarrange(ld.plot, CDR3_logos, nrow=1)
        
        if(plot.oneline==0){
          pg.all[[chain]] <- ggarrange(VJ.plot, ld_CDR3logo_plot, nrow=2,
                                       heights=c(1.3, 1))
          # Make that bar plots are slightly bigger than CDR3 ld and motif.
        } else if(plot.oneline==1){
          pg.all[[chain]] <- ggarrange(VJ.plot, ld_CDR3logo_plot, nrow=1)
        } else if(plot.oneline==2){
          pg.all[[chain]] <- ggarrange(VJ.plot, ld.plot, nrow=1, widths=c(2, 1))
        }
      }
      
      if(chain.list.output=="A" | chain.list.output=="B"){   pg.both <- pg.all[[chain.list[1]]]; div=2   }
      if(chain.list.output=="AB"){  pg.both <- ggarrange(pg.all[[chain.list[1]]], pg.all[[chain.list[2]]], ncol=2); div=1  }
      
      fig <- pg.both
      nModels_sp <- max(purrr::map_int(resSp, ~length(.x$CDR3)))
      
      if(plot.oneline==0){
        width <- 15
        height <- 5 + 1 * nModels_sp
        # We adapt the size of the figure based on the number of models present
        # as it'll need more bars and more CDR3 motifs.
      } else if(plot.oneline==1){
        width <- 20
        height <- 3 + 0.5 * nModels_sp
      } else if(plot.oneline==2){
        width <- 15
        height <- 3 + 0.5 * nModels_sp
      }
      if(!is.null(output.path)){
        filename <- paste0(output.path,"/", modelsCombinded_name)
        if (length(comb_res) > 1){
          filename <- paste0(filename, "_", sp)
          # Add species name when there where models corresponding to multiple
          # species in the data.
        }
        filename <- paste0(filename, ".", output.format)
        
        ggsave(fig, filename=filename, device=output.format,
               width = width/div, height = height, bg="white")
      }
    })
    
  }
  if(return.object != 0){
    return.list <- list()
    if(plot){
      return.list$plot <- plot.lst
    }
    return.list$stat <- es.lst
    if(!input1.list){
      return.list$processed.data <- input1.lst
    }
    return(return.list)
  }
}

